FROM python:3.9

WORKDIR /app

COPY app/ /app/
COPY model/ /app/model/
COPY app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python3", "inference.py"]
